[package]
name = "firestore-path"
version = "0.0.0"
authors = ["bouzuya <m@bouzuya.net>"]
description = "A Firestore path helper"
edition = "2021"
exclude = [".github", "docs"]
keywords = ["firestore", "gcloud", "google", "path"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/bouzuya/firestore-path"

[dependencies]
thiserror = "1.0.51"

[dev-dependencies]
anyhow = "1.0.75"
